// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ktigay/loyalty/internal/service/withdraw (interfaces: OrderRepoInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/ktigay/loyalty/internal/entity"
)

// MockOrderRepoInterface is a mock of OrderRepoInterface interface.
type MockOrderRepoInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepoInterfaceMockRecorder
}

// MockOrderRepoInterfaceMockRecorder is the mock recorder for MockOrderRepoInterface.
type MockOrderRepoInterfaceMockRecorder struct {
	mock *MockOrderRepoInterface
}

// NewMockOrderRepoInterface creates a new mock instance.
func NewMockOrderRepoInterface(ctrl *gomock.Controller) *MockOrderRepoInterface {
	mock := &MockOrderRepoInterface{ctrl: ctrl}
	mock.recorder = &MockOrderRepoInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepoInterface) EXPECT() *MockOrderRepoInterfaceMockRecorder {
	return m.recorder
}

// OrderByUser mocks base method.
func (m *MockOrderRepoInterface) OrderByUser(arg0 context.Context, arg1, arg2 string) (*entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderByUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(*entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrderByUser indicates an expected call of OrderByUser.
func (mr *MockOrderRepoInterfaceMockRecorder) OrderByUser(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderByUser", reflect.TypeOf((*MockOrderRepoInterface)(nil).OrderByUser), arg0, arg1, arg2)
}
