// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ktigay/loyalty/internal/service/order (interfaces: AccrualClientInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/ktigay/loyalty/internal/entity"
)

// MockAccrualClientInterface is a mock of AccrualClientInterface interface.
type MockAccrualClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualClientInterfaceMockRecorder
}

// MockAccrualClientInterfaceMockRecorder is the mock recorder for MockAccrualClientInterface.
type MockAccrualClientInterfaceMockRecorder struct {
	mock *MockAccrualClientInterface
}

// NewMockAccrualClientInterface creates a new mock instance.
func NewMockAccrualClientInterface(ctrl *gomock.Controller) *MockAccrualClientInterface {
	mock := &MockAccrualClientInterface{ctrl: ctrl}
	mock.recorder = &MockAccrualClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualClientInterface) EXPECT() *MockAccrualClientInterfaceMockRecorder {
	return m.recorder
}

// OrdersStatus mocks base method.
func (m *MockAccrualClientInterface) OrdersStatus(arg0 context.Context, arg1 []string) (*[]entity.Accrual, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrdersStatus", arg0, arg1)
	ret0, _ := ret[0].(*[]entity.Accrual)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrdersStatus indicates an expected call of OrdersStatus.
func (mr *MockAccrualClientInterfaceMockRecorder) OrdersStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrdersStatus", reflect.TypeOf((*MockAccrualClientInterface)(nil).OrdersStatus), arg0, arg1)
}
