// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ktigay/loyalty/internal/service/order (interfaces: RepositoryInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/ktigay/loyalty/internal/entity"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepositoryInterface) Create(arg0 context.Context, arg1, arg2 string) (*entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(*entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryInterfaceMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepositoryInterface)(nil).Create), arg0, arg1, arg2)
}

// Order mocks base method.
func (m *MockRepositoryInterface) Order(arg0 context.Context, arg1 string) (*entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Order", arg0, arg1)
	ret0, _ := ret[0].(*entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Order indicates an expected call of Order.
func (mr *MockRepositoryInterfaceMockRecorder) Order(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Order", reflect.TypeOf((*MockRepositoryInterface)(nil).Order), arg0, arg1)
}

// OrdersByStatus mocks base method.
func (m *MockRepositoryInterface) OrdersByStatus(arg0 context.Context, arg1 ...entity.OrderStatus) (*[]entity.Order, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "OrdersByStatus", varargs...)
	ret0, _ := ret[0].(*[]entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrdersByStatus indicates an expected call of OrdersByStatus.
func (mr *MockRepositoryInterfaceMockRecorder) OrdersByStatus(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrdersByStatus", reflect.TypeOf((*MockRepositoryInterface)(nil).OrdersByStatus), varargs...)
}

// OrdersByUser mocks base method.
func (m *MockRepositoryInterface) OrdersByUser(arg0 context.Context, arg1 string) (*[]entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrdersByUser", arg0, arg1)
	ret0, _ := ret[0].(*[]entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrdersByUser indicates an expected call of OrdersByUser.
func (mr *MockRepositoryInterfaceMockRecorder) OrdersByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrdersByUser", reflect.TypeOf((*MockRepositoryInterface)(nil).OrdersByUser), arg0, arg1)
}

// UpdateAll mocks base method.
func (m *MockRepositoryInterface) UpdateAll(arg0 context.Context, arg1 []entity.Order) (*[]entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAll", arg0, arg1)
	ret0, _ := ret[0].(*[]entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAll indicates an expected call of UpdateAll.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAll", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateAll), arg0, arg1)
}
