// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ktigay/loyalty/internal/service/order (interfaces: Hydrator)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/ktigay/loyalty/internal/entity"
)

// MockHydrator is a mock of Hydrator interface.
type MockHydrator struct {
	ctrl     *gomock.Controller
	recorder *MockHydratorMockRecorder
}

// MockHydratorMockRecorder is the mock recorder for MockHydrator.
type MockHydratorMockRecorder struct {
	mock *MockHydrator
}

// NewMockHydrator creates a new mock instance.
func NewMockHydrator(ctrl *gomock.Controller) *MockHydrator {
	mock := &MockHydrator{ctrl: ctrl}
	mock.recorder = &MockHydratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHydrator) EXPECT() *MockHydratorMockRecorder {
	return m.recorder
}

// Hydrate mocks base method.
func (m *MockHydrator) Hydrate(arg0 []entity.Order, arg1 []entity.AccrualOrder) ([]entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hydrate", arg0, arg1)
	ret0, _ := ret[0].([]entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hydrate indicates an expected call of Hydrate.
func (mr *MockHydratorMockRecorder) Hydrate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hydrate", reflect.TypeOf((*MockHydrator)(nil).Hydrate), arg0, arg1)
}
