// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ktigay/loyalty/internal/service/order (interfaces: HydratorInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/ktigay/loyalty/internal/entity"
)

// MockHydratorInterface is a mock of HydratorInterface interface.
type MockHydratorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHydratorInterfaceMockRecorder
}

// MockHydratorInterfaceMockRecorder is the mock recorder for MockHydratorInterface.
type MockHydratorInterfaceMockRecorder struct {
	mock *MockHydratorInterface
}

// NewMockHydratorInterface creates a new mock instance.
func NewMockHydratorInterface(ctrl *gomock.Controller) *MockHydratorInterface {
	mock := &MockHydratorInterface{ctrl: ctrl}
	mock.recorder = &MockHydratorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHydratorInterface) EXPECT() *MockHydratorInterfaceMockRecorder {
	return m.recorder
}

// Hydrate mocks base method.
func (m *MockHydratorInterface) Hydrate(arg0 []entity.Order, arg1 []entity.Accrual) (*[]entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hydrate", arg0, arg1)
	ret0, _ := ret[0].(*[]entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hydrate indicates an expected call of Hydrate.
func (mr *MockHydratorInterfaceMockRecorder) Hydrate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hydrate", reflect.TypeOf((*MockHydratorInterface)(nil).Hydrate), arg0, arg1)
}
