// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ktigay/loyalty/internal/service/order (interfaces: OrdersGetter)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/ktigay/loyalty/internal/entity"
)

// MockOrdersGetter is a mock of OrdersGetter interface.
type MockOrdersGetter struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersGetterMockRecorder
}

// MockOrdersGetterMockRecorder is the mock recorder for MockOrdersGetter.
type MockOrdersGetterMockRecorder struct {
	mock *MockOrdersGetter
}

// NewMockOrdersGetter creates a new mock instance.
func NewMockOrdersGetter(ctrl *gomock.Controller) *MockOrdersGetter {
	mock := &MockOrdersGetter{ctrl: ctrl}
	mock.recorder = &MockOrdersGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersGetter) EXPECT() *MockOrdersGetterMockRecorder {
	return m.recorder
}

// GetOrders mocks base method.
func (m *MockOrdersGetter) GetOrders(arg0 context.Context, arg1 ...string) ([]entity.AccrualOrder, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOrders", varargs...)
	ret0, _ := ret[0].([]entity.AccrualOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockOrdersGetterMockRecorder) GetOrders(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockOrdersGetter)(nil).GetOrders), varargs...)
}
