// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"log"
	"net/http"

	"github.com/gorilla/mux"
)

type securitySchemeProviderCtxKey int

const (
	NeedAuthScopes securitySchemeProviderCtxKey = iota
)

// Defines values for OrderStatus.
const (
	INVALID    OrderStatus = "INVALID"
	NEW        OrderStatus = "NEW"
	PROCESSED  OrderStatus = "PROCESSED"
	PROCESSING OrderStatus = "PROCESSING"
)

// Balance Информация по балансу пользователя.
type Balance struct {
	// Current Сумма баллов лояльности.
	Current float64 `json:"current"`

	// Withdrawn Сумма использованных за весь период регистрации баллов.
	Withdrawn float64 `json:"withdrawn"`
}

// Order defines model for Order.
type Order struct {
	// Accrual Рассчитанные баллы к начислению.
	Accrual *float64 `json:"accrual,omitempty"`

	// Number Номер заказа.
	Number string `json:"number"`

	// Status Статус заказа.
	Status     OrderStatus `json:"status"`
	UploadedAt string      `json:"uploaded_at"`
}

// OrderStatus Статус заказа.
type OrderStatus string

// Withdrawal defines model for Withdrawal.
type Withdrawal struct {
	Order       string  `json:"order"`
	ProcessedAt string  `json:"processed_at"`
	Sum         float64 `json:"sum"`
}

// GetUserBalanceJSONBody defines parameters for GetUserBalance.
type GetUserBalanceJSONBody interface{}

// PostUserBalanceWithdrawJSONBody defines parameters for PostUserBalanceWithdraw.
type PostUserBalanceWithdrawJSONBody struct {
	Order string  `json:"order"`
	Sum   float64 `json:"sum"`
}

// PostUserLoginJSONBody defines parameters for PostUserLogin.
type PostUserLoginJSONBody struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// GetUserOrdersJSONBody defines parameters for GetUserOrders.
type GetUserOrdersJSONBody interface{}

// PostUserOrdersTextBody defines parameters for PostUserOrders.
type PostUserOrdersTextBody = string

// PostUserRegisterJSONBody defines parameters for PostUserRegister.
type PostUserRegisterJSONBody struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// GetUserWithdrawsJSONBody defines parameters for GetUserWithdraws.
type GetUserWithdrawsJSONBody interface{}

// GetUserBalanceJSONRequestBody defines body for GetUserBalance for application/json ContentType.
type GetUserBalanceJSONRequestBody GetUserBalanceJSONBody

// PostUserBalanceWithdrawJSONRequestBody defines body for PostUserBalanceWithdraw for application/json ContentType.
type PostUserBalanceWithdrawJSONRequestBody PostUserBalanceWithdrawJSONBody

// PostUserLoginJSONRequestBody defines body for PostUserLogin for application/json ContentType.
type PostUserLoginJSONRequestBody PostUserLoginJSONBody

// GetUserOrdersJSONRequestBody defines body for GetUserOrders for application/json ContentType.
type GetUserOrdersJSONRequestBody GetUserOrdersJSONBody

// PostUserOrdersTextRequestBody defines body for PostUserOrders for text/plain ContentType.
type PostUserOrdersTextRequestBody = PostUserOrdersTextBody

// PostUserRegisterJSONRequestBody defines body for PostUserRegister for application/json ContentType.
type PostUserRegisterJSONRequestBody PostUserRegisterJSONBody

// GetUserWithdrawsJSONRequestBody defines body for GetUserWithdraws for application/json ContentType.
type GetUserWithdrawsJSONRequestBody GetUserWithdrawsJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получение текущего баланса счёта баллов лояльности пользователя.
	// (GET /user/balance)
	GetUserBalance(w http.ResponseWriter, r *http.Request)
	// Запрос на списание баллов с накопительного счёта в счёт оплаты нового заказа.
	// (POST /user/balance/withdraw)
	PostUserBalanceWithdraw(w http.ResponseWriter, r *http.Request)
	// Аутентификация пользователя.
	// (POST /user/login)
	PostUserLogin(w http.ResponseWriter, r *http.Request)
	// Получение списка загруженных пользователем номеров заказов, статусов их обработки и информации о начислениях.
	// (GET /user/orders)
	GetUserOrders(w http.ResponseWriter, r *http.Request)
	// Загрузка пользователем номера заказа для расчёта.
	// (POST /user/orders)
	PostUserOrders(w http.ResponseWriter, r *http.Request)
	// Регистрация пользователя.
	// (POST /user/register)
	PostUserRegister(w http.ResponseWriter, r *http.Request)
	// Получение информации о выводе средств с накопительного счёта пользователем.
	// (GET /user/withdrawals)
	GetUserWithdraws(w http.ResponseWriter, r *http.Request)
}

// Server handler func.
type HandlerFunc func(w http.ResponseWriter, r *http.Request)

// Server implement ServerInterface.
type Server struct {
	// Получение текущего баланса счёта баллов лояльности пользователя.
	// (GET /user/balance)
	GetUserBalanceHandler HandlerFunc
	// Запрос на списание баллов с накопительного счёта в счёт оплаты нового заказа.
	// (POST /user/balance/withdraw)
	PostUserBalanceWithdrawHandler HandlerFunc
	// Аутентификация пользователя.
	// (POST /user/login)
	PostUserLoginHandler HandlerFunc
	// Получение списка загруженных пользователем номеров заказов, статусов их обработки и информации о начислениях.
	// (GET /user/orders)
	GetUserOrdersHandler HandlerFunc
	// Загрузка пользователем номера заказа для расчёта.
	// (POST /user/orders)
	PostUserOrdersHandler HandlerFunc
	// Регистрация пользователя.
	// (POST /user/register)
	PostUserRegisterHandler HandlerFunc
	// Получение информации о выводе средств с накопительного счёта пользователем.
	// (GET /user/withdrawals)
	GetUserWithdrawsHandler HandlerFunc
}

// GetUserBalance wrapper for GetUserBalanceHandler.
func (s Server) GetUserBalance(w http.ResponseWriter, r *http.Request) {
	if s.GetUserBalanceHandler == nil {
		log.Fatal("unimplemented method")
	}

	s.GetUserBalanceHandler(w, r)
}

// PostUserBalanceWithdraw wrapper for PostUserBalanceWithdrawHandler.
func (s Server) PostUserBalanceWithdraw(w http.ResponseWriter, r *http.Request) {
	if s.PostUserBalanceWithdrawHandler == nil {
		log.Fatal("unimplemented method")
	}

	s.PostUserBalanceWithdrawHandler(w, r)
}

// PostUserLogin wrapper for PostUserLoginHandler.
func (s Server) PostUserLogin(w http.ResponseWriter, r *http.Request) {
	if s.PostUserLoginHandler == nil {
		log.Fatal("unimplemented method")
	}

	s.PostUserLoginHandler(w, r)
}

// GetUserOrders wrapper for GetUserOrdersHandler.
func (s Server) GetUserOrders(w http.ResponseWriter, r *http.Request) {
	if s.GetUserOrdersHandler == nil {
		log.Fatal("unimplemented method")
	}

	s.GetUserOrdersHandler(w, r)
}

// PostUserOrders wrapper for PostUserOrdersHandler.
func (s Server) PostUserOrders(w http.ResponseWriter, r *http.Request) {
	if s.PostUserOrdersHandler == nil {
		log.Fatal("unimplemented method")
	}

	s.PostUserOrdersHandler(w, r)
}

// PostUserRegister wrapper for PostUserRegisterHandler.
func (s Server) PostUserRegister(w http.ResponseWriter, r *http.Request) {
	if s.PostUserRegisterHandler == nil {
		log.Fatal("unimplemented method")
	}

	s.PostUserRegisterHandler(w, r)
}

// GetUserWithdraws wrapper for GetUserWithdrawsHandler.
func (s Server) GetUserWithdraws(w http.ResponseWriter, r *http.Request) {
	if s.GetUserWithdrawsHandler == nil {
		log.Fatal("unimplemented method")
	}

	s.GetUserWithdrawsHandler(w, r)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetUserBalance operation middleware
func (siw *ServerInterfaceWrapper) GetUserBalance(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, NeedAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserBalance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserBalanceWithdraw operation middleware
func (siw *ServerInterfaceWrapper) PostUserBalanceWithdraw(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, NeedAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserBalanceWithdraw(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserLogin operation middleware
func (siw *ServerInterfaceWrapper) PostUserLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserOrders operation middleware
func (siw *ServerInterfaceWrapper) GetUserOrders(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, NeedAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserOrders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserOrders operation middleware
func (siw *ServerInterfaceWrapper) PostUserOrders(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, NeedAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserOrders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserRegister operation middleware
func (siw *ServerInterfaceWrapper) PostUserRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserWithdraws operation middleware
func (siw *ServerInterfaceWrapper) GetUserWithdraws(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, NeedAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserWithdraws(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/user/balance", wrapper.GetUserBalance).Methods("GET")

	r.HandleFunc(options.BaseURL+"/user/balance/withdraw", wrapper.PostUserBalanceWithdraw).Methods("POST")

	r.HandleFunc(options.BaseURL+"/user/login", wrapper.PostUserLogin).Methods("POST")

	r.HandleFunc(options.BaseURL+"/user/orders", wrapper.GetUserOrders).Methods("GET")

	r.HandleFunc(options.BaseURL+"/user/orders", wrapper.PostUserOrders).Methods("POST")

	r.HandleFunc(options.BaseURL+"/user/register", wrapper.PostUserRegister).Methods("POST")

	r.HandleFunc(options.BaseURL+"/user/withdrawals", wrapper.GetUserWithdraws).Methods("GET")

	return r
}
