// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ktigay/loyalty/internal/handler/user (interfaces: AuthInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/ktigay/loyalty/internal/entity"
)

// MockAuthInterface is a mock of AuthInterface interface.
type MockAuthInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthInterfaceMockRecorder
}

// MockAuthInterfaceMockRecorder is the mock recorder for MockAuthInterface.
type MockAuthInterfaceMockRecorder struct {
	mock *MockAuthInterface
}

// NewMockAuthInterface creates a new mock instance.
func NewMockAuthInterface(ctrl *gomock.Controller) *MockAuthInterface {
	mock := &MockAuthInterface{ctrl: ctrl}
	mock.recorder = &MockAuthInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthInterface) EXPECT() *MockAuthInterfaceMockRecorder {
	return m.recorder
}

// SetIdentity mocks base method.
func (m *MockAuthInterface) SetIdentity(arg0 *http.Request, arg1 http.ResponseWriter, arg2 *entity.Identity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIdentity", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetIdentity indicates an expected call of SetIdentity.
func (mr *MockAuthInterfaceMockRecorder) SetIdentity(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIdentity", reflect.TypeOf((*MockAuthInterface)(nil).SetIdentity), arg0, arg1, arg2)
}
