// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ktigay/loyalty/internal/handler/user (interfaces: Auth)

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/ktigay/loyalty/internal/entity"
)

// MockAuth is a mock of Auth interface.
type MockAuth struct {
	ctrl     *gomock.Controller
	recorder *MockAuthMockRecorder
}

// MockAuthMockRecorder is the mock recorder for MockAuth.
type MockAuthMockRecorder struct {
	mock *MockAuth
}

// NewMockAuth creates a new mock instance.
func NewMockAuth(ctrl *gomock.Controller) *MockAuth {
	mock := &MockAuth{ctrl: ctrl}
	mock.recorder = &MockAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuth) EXPECT() *MockAuthMockRecorder {
	return m.recorder
}

// SetIdentity mocks base method.
func (m *MockAuth) SetIdentity(arg0 *http.Request, arg1 http.ResponseWriter, arg2 *entity.Identity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIdentity", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetIdentity indicates an expected call of SetIdentity.
func (mr *MockAuthMockRecorder) SetIdentity(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIdentity", reflect.TypeOf((*MockAuth)(nil).SetIdentity), arg0, arg1, arg2)
}
