// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ktigay/loyalty/internal/handler/balance (interfaces: WithdrawServiceInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/ktigay/loyalty/internal/entity"
)

// MockWithdrawServiceInterface is a mock of WithdrawServiceInterface interface.
type MockWithdrawServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawServiceInterfaceMockRecorder
}

// MockWithdrawServiceInterfaceMockRecorder is the mock recorder for MockWithdrawServiceInterface.
type MockWithdrawServiceInterfaceMockRecorder struct {
	mock *MockWithdrawServiceInterface
}

// NewMockWithdrawServiceInterface creates a new mock instance.
func NewMockWithdrawServiceInterface(ctrl *gomock.Controller) *MockWithdrawServiceInterface {
	mock := &MockWithdrawServiceInterface{ctrl: ctrl}
	mock.recorder = &MockWithdrawServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawServiceInterface) EXPECT() *MockWithdrawServiceInterfaceMockRecorder {
	return m.recorder
}

// MakeWithdraw mocks base method.
func (m *MockWithdrawServiceInterface) MakeWithdraw(arg0 context.Context, arg1, arg2 string, arg3 int64) (*entity.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeWithdraw", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*entity.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeWithdraw indicates an expected call of MakeWithdraw.
func (mr *MockWithdrawServiceInterfaceMockRecorder) MakeWithdraw(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeWithdraw", reflect.TypeOf((*MockWithdrawServiceInterface)(nil).MakeWithdraw), arg0, arg1, arg2, arg3)
}

// Withdrawals mocks base method.
func (m *MockWithdrawServiceInterface) Withdrawals(arg0 context.Context, arg1 string) (*[]entity.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdrawals", arg0, arg1)
	ret0, _ := ret[0].(*[]entity.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Withdrawals indicates an expected call of Withdrawals.
func (mr *MockWithdrawServiceInterfaceMockRecorder) Withdrawals(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdrawals", reflect.TypeOf((*MockWithdrawServiceInterface)(nil).Withdrawals), arg0, arg1)
}
