// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ktigay/loyalty/internal/service/order/task (interfaces: BalanceRepoInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/ktigay/loyalty/internal/entity"
)

// MockBalanceRepoInterface is a mock of BalanceRepoInterface interface.
type MockBalanceRepoInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceRepoInterfaceMockRecorder
}

// MockBalanceRepoInterfaceMockRecorder is the mock recorder for MockBalanceRepoInterface.
type MockBalanceRepoInterfaceMockRecorder struct {
	mock *MockBalanceRepoInterface
}

// NewMockBalanceRepoInterface creates a new mock instance.
func NewMockBalanceRepoInterface(ctrl *gomock.Controller) *MockBalanceRepoInterface {
	mock := &MockBalanceRepoInterface{ctrl: ctrl}
	mock.recorder = &MockBalanceRepoInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceRepoInterface) EXPECT() *MockBalanceRepoInterfaceMockRecorder {
	return m.recorder
}

// IncreaseCurrent mocks base method.
func (m *MockBalanceRepoInterface) IncreaseCurrent(arg0 context.Context, arg1 string, arg2 int64) (*entity.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseCurrent", arg0, arg1, arg2)
	ret0, _ := ret[0].(*entity.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncreaseCurrent indicates an expected call of IncreaseCurrent.
func (mr *MockBalanceRepoInterfaceMockRecorder) IncreaseCurrent(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseCurrent", reflect.TypeOf((*MockBalanceRepoInterface)(nil).IncreaseCurrent), arg0, arg1, arg2)
}
