// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ktigay/loyalty/internal/service/order/task (interfaces: StatusGetterInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/ktigay/loyalty/internal/entity"
)

// MockStatusGetterInterface is a mock of StatusGetterInterface interface.
type MockStatusGetterInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStatusGetterInterfaceMockRecorder
}

// MockStatusGetterInterfaceMockRecorder is the mock recorder for MockStatusGetterInterface.
type MockStatusGetterInterfaceMockRecorder struct {
	mock *MockStatusGetterInterface
}

// NewMockStatusGetterInterface creates a new mock instance.
func NewMockStatusGetterInterface(ctrl *gomock.Controller) *MockStatusGetterInterface {
	mock := &MockStatusGetterInterface{ctrl: ctrl}
	mock.recorder = &MockStatusGetterInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusGetterInterface) EXPECT() *MockStatusGetterInterfaceMockRecorder {
	return m.recorder
}

// ReceiveStatus mocks base method.
func (m *MockStatusGetterInterface) ReceiveStatus(arg0 context.Context, arg1 []entity.Order) (*[]entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveStatus", arg0, arg1)
	ret0, _ := ret[0].(*[]entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReceiveStatus indicates an expected call of ReceiveStatus.
func (mr *MockStatusGetterInterfaceMockRecorder) ReceiveStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveStatus", reflect.TypeOf((*MockStatusGetterInterface)(nil).ReceiveStatus), arg0, arg1)
}
