// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ktigay/loyalty/internal/service/order/task (interfaces: OrderRepoInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/ktigay/loyalty/internal/entity"
)

// MockOrderRepoInterface is a mock of OrderRepoInterface interface.
type MockOrderRepoInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepoInterfaceMockRecorder
}

// MockOrderRepoInterfaceMockRecorder is the mock recorder for MockOrderRepoInterface.
type MockOrderRepoInterfaceMockRecorder struct {
	mock *MockOrderRepoInterface
}

// NewMockOrderRepoInterface creates a new mock instance.
func NewMockOrderRepoInterface(ctrl *gomock.Controller) *MockOrderRepoInterface {
	mock := &MockOrderRepoInterface{ctrl: ctrl}
	mock.recorder = &MockOrderRepoInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepoInterface) EXPECT() *MockOrderRepoInterfaceMockRecorder {
	return m.recorder
}

// OrdersByStatus mocks base method.
func (m *MockOrderRepoInterface) OrdersByStatus(arg0 context.Context, arg1 ...entity.OrderStatus) (*[]entity.Order, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "OrdersByStatus", varargs...)
	ret0, _ := ret[0].(*[]entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrdersByStatus indicates an expected call of OrdersByStatus.
func (mr *MockOrderRepoInterfaceMockRecorder) OrdersByStatus(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrdersByStatus", reflect.TypeOf((*MockOrderRepoInterface)(nil).OrdersByStatus), varargs...)
}

// UpdateAll mocks base method.
func (m *MockOrderRepoInterface) UpdateAll(arg0 context.Context, arg1 []entity.Order) (*[]entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAll", arg0, arg1)
	ret0, _ := ret[0].(*[]entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAll indicates an expected call of UpdateAll.
func (mr *MockOrderRepoInterfaceMockRecorder) UpdateAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAll", reflect.TypeOf((*MockOrderRepoInterface)(nil).UpdateAll), arg0, arg1)
}
