// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ktigay/loyalty/internal/service/order/task (interfaces: StatusGetter)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/ktigay/loyalty/internal/entity"
)

// MockStatusGetter is a mock of StatusGetter interface.
type MockStatusGetter struct {
	ctrl     *gomock.Controller
	recorder *MockStatusGetterMockRecorder
}

// MockStatusGetterMockRecorder is the mock recorder for MockStatusGetter.
type MockStatusGetterMockRecorder struct {
	mock *MockStatusGetter
}

// NewMockStatusGetter creates a new mock instance.
func NewMockStatusGetter(ctrl *gomock.Controller) *MockStatusGetter {
	mock := &MockStatusGetter{ctrl: ctrl}
	mock.recorder = &MockStatusGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusGetter) EXPECT() *MockStatusGetterMockRecorder {
	return m.recorder
}

// ReceiveStatus mocks base method.
func (m *MockStatusGetter) ReceiveStatus(arg0 context.Context, arg1 []entity.Order) ([]entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveStatus", arg0, arg1)
	ret0, _ := ret[0].([]entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReceiveStatus indicates an expected call of ReceiveStatus.
func (mr *MockStatusGetterMockRecorder) ReceiveStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveStatus", reflect.TypeOf((*MockStatusGetter)(nil).ReceiveStatus), arg0, arg1)
}
