// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ktigay/loyalty/internal/db (interfaces: PgxConn)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v5"
)

// MockPgxConn is a mock of PgxConn interface.
type MockPgxConn struct {
	ctrl     *gomock.Controller
	recorder *MockPgxConnMockRecorder
}

// MockPgxConnMockRecorder is the mock recorder for MockPgxConn.
type MockPgxConnMockRecorder struct {
	mock *MockPgxConn
}

// NewMockPgxConn creates a new mock instance.
func NewMockPgxConn(ctrl *gomock.Controller) *MockPgxConn {
	mock := &MockPgxConn{ctrl: ctrl}
	mock.recorder = &MockPgxConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPgxConn) EXPECT() *MockPgxConnMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockPgxConn) BeginTx(arg0 context.Context, arg1 pgx.TxOptions) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", arg0, arg1)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockPgxConnMockRecorder) BeginTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockPgxConn)(nil).BeginTx), arg0, arg1)
}
