// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ktigay/loyalty/internal/db (interfaces: TxFacade)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v5"
)

// MockTxFacade is a mock of TxFacade interface.
type MockTxFacade struct {
	ctrl     *gomock.Controller
	recorder *MockTxFacadeMockRecorder
}

// MockTxFacadeMockRecorder is the mock recorder for MockTxFacade.
type MockTxFacadeMockRecorder struct {
	mock *MockTxFacade
}

// NewMockTxFacade creates a new mock instance.
func NewMockTxFacade(ctrl *gomock.Controller) *MockTxFacade {
	mock := &MockTxFacade{ctrl: ctrl}
	mock.recorder = &MockTxFacadeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxFacade) EXPECT() *MockTxFacadeMockRecorder {
	return m.recorder
}

// RunInTx mocks base method.
func (m *MockTxFacade) RunInTx(arg0 context.Context, arg1 pgx.TxOptions, arg2 func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MockTxFacadeMockRecorder) RunInTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*MockTxFacade)(nil).RunInTx), arg0, arg1, arg2)
}
