// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ktigay/loyalty/internal/db (interfaces: TxFacadeInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v5"
)

// MockTxFacadeInterface is a mock of TxFacadeInterface interface.
type MockTxFacadeInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTxFacadeInterfaceMockRecorder
}

// MockTxFacadeInterfaceMockRecorder is the mock recorder for MockTxFacadeInterface.
type MockTxFacadeInterfaceMockRecorder struct {
	mock *MockTxFacadeInterface
}

// NewMockTxFacadeInterface creates a new mock instance.
func NewMockTxFacadeInterface(ctrl *gomock.Controller) *MockTxFacadeInterface {
	mock := &MockTxFacadeInterface{ctrl: ctrl}
	mock.recorder = &MockTxFacadeInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxFacadeInterface) EXPECT() *MockTxFacadeInterfaceMockRecorder {
	return m.recorder
}

// RunInTx mocks base method.
func (m *MockTxFacadeInterface) RunInTx(arg0 context.Context, arg1 pgx.TxOptions, arg2 func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MockTxFacadeInterfaceMockRecorder) RunInTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*MockTxFacadeInterface)(nil).RunInTx), arg0, arg1, arg2)
}
