// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ktigay/loyalty/internal/service/user (interfaces: BalanceRepoInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBalanceRepoInterface is a mock of BalanceRepoInterface interface.
type MockBalanceRepoInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceRepoInterfaceMockRecorder
}

// MockBalanceRepoInterfaceMockRecorder is the mock recorder for MockBalanceRepoInterface.
type MockBalanceRepoInterfaceMockRecorder struct {
	mock *MockBalanceRepoInterface
}

// NewMockBalanceRepoInterface creates a new mock instance.
func NewMockBalanceRepoInterface(ctrl *gomock.Controller) *MockBalanceRepoInterface {
	mock := &MockBalanceRepoInterface{ctrl: ctrl}
	mock.recorder = &MockBalanceRepoInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceRepoInterface) EXPECT() *MockBalanceRepoInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBalanceRepoInterface) Create(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBalanceRepoInterfaceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBalanceRepoInterface)(nil).Create), arg0, arg1)
}
